# Generated by Django 2.0.7 on 2018-07-29 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=400)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemTypes', to='orders.ItemType')),
            ],
        ),
    ]
