# Generated by Django 2.0.7 on 2018-07-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('sm', 'Small'), ('rg', 'Regular'), ('lg', 'Large')], default='rg', max_length=2),
        ),
    ]
