# Generated by Django 2.0.7 on 2018-07-29 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180729_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Item'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='item_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ItemType'),
        ),
    ]
