# Generated by Django 2.0.7 on 2018-07-29 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180729_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='orders.Item'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='orders.Item'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='orders.ItemType'),
        ),
    ]
