# Generated by Django 2.0.7 on 2018-08-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_ordereditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='state',
            field=models.CharField(choices=[('01', 'New'), ('02', 'Ordered'), ('03', 'Complete')], default='01', max_length=2),
        ),
    ]
