# Generated by Django 2.0.7 on 2018-08-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderedtopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='num_toppings',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three'), (5, 'Five')], default=0),
            preserve_default=False,
        ),
    ]
